services:
  postgres:
    image: postgres:16.3-alpine3.20
    restart: always
    container_name: ${CONTAINER_NAME:?CONTAINER_NAME is not set}
    ports:
      - "5432:5432"
    volumes:
      - ${VOLUME_PATH:?VOLUME_PATH is not set}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER:?POSTGRES_USER is not set}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD:?POSTGRES_PASSWORD is not set}
      POSTGRES_DB: ${POSTGRESQL_DB:?POSTGRES_DB is not set}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:?POSTGRES_USER is not set} -d ${POSTGRES_DB:?POSTGRES_DB is not set}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
  
  pgbouncer:
    image: bitnami/pgbouncer:latest
    restart: always
    ports:
      - "6432:6432"
    environment:
      POSTGRESQL_HOST: postgres
      POSTGRESQL_USERNAME: ${POSTGRESQL_USER:?POSTGRES_USER is not set}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD:?POSTGRES_PASSWORD is not set}
      POSTGRESQL_PORT: ${POSTGRESQL_PORT:?POSTGRES_PORT is not set}
      PGBOUNCER_DATABASE: ${POSTGRESQL_DB:?POSTGRES_DB is not set}
    depends_on:
      postgres:
        condition: service_healthy